extends SceneTree

## Regression test for dig/chop running through the generic toil executor
## (game/scripts/core/jobs/toil_executor.gd) rather than kind-specific
## branches inlined in WorldState (colonist-ai.md 3.3). EXPECTED_HASH is a
## literal captured from this exact scripted run: an unchanged hash across a
## change to WorldState/ToilExecutor proves that route/work stepping,
## MOVE_TICKS_PER_TILE/WORK_TICKS and rerouting behave identically.
##
## The literals legitimately change in two situations, and are then recaptured
## by running this test:
## - Snapshot-shape changes: state_hash() gains a new key or field (item ids,
##   zones, needs, labour table, tools, health, faction id, scheduler queue
##   fields, calendar alerts, world dimensions, incident scheduler state, RNG
##   streams, ...). A new key changes the hash even when, as here, it stays
##   empty.
## - Stepping changes that genuinely alter this scenario: dig/chop declaring
##   needs_tool and a fetch_tool toil (so _build_world() places a pick and an
##   axe for each colonist); the scheduler's activation route search and
##   fetch_tool travel sharing one per-colonist per-tick routing allowance
##   (ADR 004), which defers a colonist's first travel search by one tick;
##   needs decaying per day instead of per tick (ADR 024); and dig turning its
##   tile into trench, spawning a ground sand item and consuming a seeded
##   find-table roll (ADR 026).
##
## COLONY_EXPECTED_HASH is the value of state_hash(false), which excludes the
## entire incident contribution, so incident-shape changes never move it.
## test_incidents.gd's _check_disabled_reproduces_pre_incident_hash() and
## test_world_state_determinism.gd's
## _check_incidents_disabled_matches_pre_incident_baseline() both rely on it
## as their pre-incident baseline (ADR 004). It does move when an
## unconditional key is added, such as the dig-find RNG stream's seed/state.
##
## Some additions deliberately leave both literals unaffected: the per-object
## faction map is not snapshotted, and an incident actor's "autonomous"
## queue-entry flag (ADR 014) is stored only when true, so a world that never
## submits one keeps its exact snapshot shape.
##
## The fixture separates its two corridors with a rock buffer row (see
## _build_world()) so that no colonist can path back across an already-dug
## trench tile and become trapped. Route search still treats trench as
## passable terrain; only the trap-on-entry arrival check is avoided here, and
## test_trapped_actors.gd exercises it on purpose.

const WorldType = preload("res://scripts/core/world_state.gd")
const ToilExecutorType = preload("res://scripts/core/jobs/toil_executor.gd")
const JOBS_CONTENT_PATH := "res://content/jobs.json"

## Both literals also cover snapshot keys that stay empty in this run, because
## each key changes the dict shape regardless of its value: the colonist
## "combat" component (content/actors.json, backfilled by
## WorldState._ensure_combat()), world._object_health, CombatGiver's
## excluded-flee-destination set, "suspended_work_progress",
## "approach_job_targets" (ADR 033), RescueGiver's
## "rescue_victim_assignments" (hashed as a sorted {jobId, victimId} array so
## insertion order does not matter), "construction_sites" (ADR 040), and the
## colonist "hands" list (ADR 037).
## Regenerated by running this test under Godot, per AGENTS.md's "never
## hand-derive a hash" rule.
const EXPECTED_HASH := 1457403841
const COLONY_EXPECTED_HASH := 828510519
const TOTAL_TICKS := 260

var _failed := false

func _init() -> void:
	_check_jobs_content_file()

	var world := _build_world(190190)
	_run_scenario(world)
	var ticks := 0
	while ticks < TOTAL_TICKS:
		world.tick()
		ticks += 1

	var completed := 0
	for job in world.get_jobs():
		if job["status"] == "completed":
			completed += 1
	_expect(completed == 6, "all six scripted dig/chop orders must complete within the fixed tick budget (got %d)" % completed)
	for colonist in world._colonists:
		_expect(colonist.get("trapped") == null,
			"no colonist should be trapped by the end of this scenario (got %s on %s)" % [colonist.get("trapped"), colonist["id"]])

	var hash_value := world.state_hash()
	_expect(hash_value == EXPECTED_HASH,
		"state_hash() must match the literal captured before the toils refactor (got %d, expected %d)" % [hash_value, EXPECTED_HASH])
	var colony_hash_value := world.state_hash(false)
	_expect(colony_hash_value == COLONY_EXPECTED_HASH,
		"state_hash(false)'s colony-only projection must match the unchanging pre-incident baseline (got %d, expected %d)" % [colony_hash_value, COLONY_EXPECTED_HASH])

	if _failed:
		quit(1)
		return
	print("test_toils_dig_chop_regression: PASS")
	quit(0)

func _expect(condition: bool, message: String) -> void:
	if not condition:
		_failed = true
		push_error(message)

## game/content/jobs.json must parse as JSON and declare exactly the dig,
## mine, chop, forage, till, sow, haul, site_fetch, site_work, eat_food,
## drink_water, sleep, incident, escape_trench, flee, rescue and approach
## kinds, each with a toils
## array using only the vocabulary names from colonist-ai.md 3.3 (reserve,
## go_to, pick_up, work, place, consume, fetch_tool, release_all).
func _check_jobs_content_file() -> void:
	var file := FileAccess.open(JOBS_CONTENT_PATH, FileAccess.READ)
	if file == null:
		_expect(false, "could not open %s" % JOBS_CONTENT_PATH)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	_expect(typeof(parsed) != TYPE_NIL, "%s must parse as JSON" % JOBS_CONTENT_PATH)
	if typeof(parsed) != TYPE_DICTIONARY or typeof(parsed.get("jobs")) != TYPE_ARRAY:
		_expect(false, "%s must contain a top-level 'jobs' array" % JOBS_CONTENT_PATH)
		return
	var kinds: Dictionary = {}
	for entry in parsed["jobs"]:
		_expect(typeof(entry) == TYPE_DICTIONARY, "every jobs.json entry must be an object")
		if typeof(entry) != TYPE_DICTIONARY:
			continue
		var kind := String(entry.get("kind", ""))
		kinds[kind] = true
		_expect(typeof(entry.get("toils")) == TYPE_ARRAY and not (entry["toils"] as Array).is_empty(),
			"%s toils must be a non-empty array" % kind)
		for toil in entry.get("toils", []):
			_expect(ToilExecutorType.is_known_toil(String(toil)),
				"%s declares unknown toil '%s'" % [kind, toil])
	_expect(kinds.size() == 17 and kinds.has("dig") and kinds.has("mine") and kinds.has("chop") and kinds.has("forage") and kinds.has("till")
			and kinds.has("sow") and kinds.has("haul") and kinds.has("site_fetch") and kinds.has("site_work") and kinds.has("eat_food") and kinds.has("drink_water") and kinds.has("sleep")
			and kinds.has("incident") and kinds.has("escape_trench") and kinds.has("flee") and kinds.has("rescue") and kinds.has("approach"),
		"jobs.json must declare exactly the dig, mine, chop, forage, till, sow, haul, site_fetch, site_work, eat_food, drink_water, sleep, incident, escape_trench, flee, rescue and approach kinds (got %s)" % [kinds.keys()])

func _command(world: WorldType, command_id: String, kind: String, payload: Dictionary) -> Dictionary:
	return world.apply({"actor": "test", "command_id": command_id, "tick": world.get_tick(),
		"type": kind, "payload": payload})

## Two parallel corridors (y=0, y=2; x=0..9) with a tree at the far end of
## each row and a one-tile rock buffer (y=1) between them; everything else is
## rock. Two colonists start at the near end of each row so dig/chop targets,
## routing and the fair scheduler (unrestricted "assignee") all have real
## work to do -- each colonist does both a dig and a chop order on its own
## row, so it swaps between pick and axe. The buffer row makes the two
## corridors unreachable from one another: with adjacent corridors, a colonist
## assigned to a farther target under the fair scheduler's nearest/priority
## ordering could path diagonally back across a row-mate's already-dug trench
## tile and fall in. test_trapped_actors.gd covers that on purpose; this
## scenario is about dig/chop/toil stepping, so its geometry avoids the trap
## rather than restricting assignment.
func _build_world(seed_value: int) -> WorldType:
	var world := WorldType.new(seed_value)
	world._tiles.fill(WorldType.TILE_ROCK)
	# Clear any generator-placed berry_bush (ADR 020) before overwriting
	# tiles: a stray one would leak into state_hash() even though it cannot
	# affect this fixture's two corridors, moving EXPECTED_HASH /
	# COLONY_EXPECTED_HASH for a reason unrelated to what either documents.
	world._objects.clear()
	world._object_factions.clear()
	for x in range(0, 10):
		world._tiles[world._tile_index(x, 0)] = WorldType.TILE_SOIL
		world._tiles[world._tile_index(x, 2)] = WorldType.TILE_SOIL
	world._tiles[world._tile_index(9, 0)] = WorldType.TILE_TREE
	world._tiles[world._tile_index(9, 2)] = WorldType.TILE_TREE
	world._colonists.clear()
	world._colonists.append({"id": "colonist_0", "kind": "colonist", "x": 0, "y": 0, "route": null, "work": null})
	world._colonists.append({"id": "colonist_1", "kind": "colonist", "x": 0, "y": 2, "route": null, "work": null})
	# Axe sits past every dig target (x=8, just short of the tree at x=9),
	# pick at the start (x=0, before every dig target) -- see _run_scenario()'s
	# own comment for why this placement, combined with its priorities, keeps
	# every fetch_tool trip and every dig/chop leg strictly forward, so no
	# colonist ever re-lands on a trench tile it (or nothing else, these rows
	# are unreachable from one another) already dug.
	world.spawn_ground_tool_item("pick", 0, 0)
	world.spawn_ground_tool_item("axe", 8, 0)
	world.spawn_ground_tool_item("pick", 0, 2)
	world.spawn_ground_tool_item("axe", 8, 2)
	return world

## Submits a scripted sequence of dig and chop orders, ticking between
## submissions so some orders are still queued/blocked when the next lands --
## exercising reserve/go_to/work/release_all across overlapping jobs, not
## just one job at a time. Unrestricted (no "assignee"): the fair scheduler
## picks whichever colonist is free/nearest. Priority varies (every dig
## outranks every chop, 2 vs 1), deliberately, so that within a row every
## dig is always served before that row's chop regardless of submission
## order/aging (global_assignment.gd's PRIORITY_WEIGHT=16 dwarfs this
## scenario's few-tick submission spread), and dig_1/dig_2/dig_4 (equal
## priority, so FIFO by submission order/ordinal) are served in strictly
## ascending x. A colonist therefore always walks its row purely rightward
## -- pick already in hand from its first dig, straight through 3, 5, 7 --
## and only afterwards, once, forward again to the axe depot at 8 and the
## tree at 9: no dig target is ever revisited after the trap-on-entry rule
## turns it to trench.
func _run_scenario(world: WorldType) -> void:
	_command(world, "dig_1", "dig", {"x": 3, "y": 0, "priority": 2})
	_command(world, "dig_2", "dig", {"x": 5, "y": 0, "priority": 2})
	world.tick()
	world.tick()
	_command(world, "chop_1", "chop", {"x": 9, "y": 0, "priority": 1})
	_command(world, "dig_3", "dig", {"x": 3, "y": 2, "priority": 2})
	world.tick()
	world.tick()
	world.tick()
	_command(world, "chop_2", "chop", {"x": 9, "y": 2, "priority": 1})
	_command(world, "dig_4", "dig", {"x": 7, "y": 0, "priority": 2})
